[package]
name = "rsa"
version = "0.2.0"
authors = ["ph"]
edition = "2018"

[lib]
name = "rsa"
path = "src/lib.rs"

[dependencies]
num-traits = "0.1"
openssl = "0.9"

[dependencies.bignum]
path = "../bignum"
