[package]
name = "srp"
version = "0.2.0"
authors = ["ph"]
edition = "2018"

[dependencies]
byteorder = "0.5"
num = "0.1"
rand = "0.3" 
sha2 = "0.6"

[dependencies.bignum]
path = "../bignum"

[dependencies.mac]
path = "../mac"

[dependencies.serialize]
path = "../serialize"
