[package]
name = "dsa"
version = "0.1.0"
authors = ["Philipp Hartwig <ph@phhart.de>"]

[dependencies]
num-traits = "0.1"
openssl = "0.9"

[dependencies.bignum]
path = "../bignum"

[dependencies.rsa]
path = "../rsa"
