[package]
name = "dsa"
version = "0.2.0"
authors = ["Philipp Hartwig <ph@phhart.de>"]
edition = "2018"

[dependencies]
digest = "0.7"
num-traits = "0.1"
openssl = "0.9"
sha-1 = "0.7"

[dependencies.bignum]
path = "../bignum"

[dependencies.rsa]
path = "../rsa"
