[package]
name = "hmac_server"
version = "0.0.1"
authors = ["ph"]

[dependencies]
hyper = "0.10"
iron = "0.5"
params = "0.6"

[dependencies.mac]
path = "../mac"

[dependencies.serialize]
path = "../serialize"
